ACCOUNTS = []
SIGNING_KEY = ""
NETWORK_PASSPHRASE = "Test SDF Network ; September 2015"

TRANSFER_SERVER = "http://localhost:8000/sep6"
TRANSFER_SERVER_SEP0024 = "http://localhost:8000/sep24"
WEB_AUTH_ENDPOINT = "http://localhost:8000/auth"
KYC_SERVER = "http://localhost:8000/kyc"
DIRECT_PAYMENT_SERVER = "http://localhost:8000/sep31"
ANCHOR_QUOTE_SERVER = "http://localhost:8000/sep38"

[[CURRENCIES]]
code = "PYSC"
issuer = "GCDNJUBQSX7AJWLJACMJ7I4BC3Z47BQUTMHEICZLE6MU4KQBRYG5JY6B"
status = "test"
is_asset_anchored = false
desc = "Paysec Asset representing a package."

[DOCUMENTATION]
ORG_NAME = "Stellar Development Foundation"
ORG_URL = "https://stellar.org"
ORG_DESCRIPTION = "The Stellar Development Foundation (SDF) is a non-profit organization whose mission is to create equitable access to the global financial system."
ORG_GITHUB = "stellar"
